import * as THREE from "three";
import type { BridgeCrossingCandidate, GeneratedBridge } from "./bridges";

/** Dedicated, presentation-only renderer for plain span-POI records. */
export class BridgeMeshFactory {
 private readonly box=new THREE.BoxGeometry(1,1,1);
 private readonly cylinder=new THREE.CylinderGeometry(.5,.5,1,8);
 private readonly materials={wood:new THREE.MeshStandardMaterial({color:0x806244,roughness:1}),darkWood:new THREE.MeshStandardMaterial({color:0x4d3928,roughness:1}),rope:new THREE.MeshStandardMaterial({color:0x9a825a,roughness:1}),stone:new THREE.MeshStandardMaterial({color:0x817d73,roughness:1}),stoneDark:new THREE.MeshStandardMaterial({color:0x625f58,roughness:1})};
 private component(name:string,geometry:THREE.BufferGeometry,material:THREE.Material,scale:[number,number,number],position:[number,number,number]):THREE.Mesh{const mesh=new THREE.Mesh(geometry,material);mesh.name=name;mesh.scale.set(...scale);mesh.position.set(...position);return mesh;}
 create(bridge:GeneratedBridge):THREE.Group{const root=new THREE.Group();root.name=`bridge:${bridge.archetype}:${bridge.id}`;root.userData={bridgeId:bridge.id,archetype:bridge.archetype,variant:bridge.variant,shadowCasterCount:bridge.shadowCaster?1:0};root.position.set(bridge.crossingCentre.x,bridge.crossingCentre.y,bridge.crossingCentre.z);root.rotation.y=-Math.atan2(bridge.collision.direction.z,bridge.collision.direction.x);const deck=bridge.collision.surfaces[0]!,span=bridge.collision.deckLength,width=bridge.collision.deckWidth,stone=bridge.archetype==="stone-bridge",heavy=bridge.archetype==="heavy-timber-bridge";root.add(this.component("bridge-deck",this.box,stone?this.materials.stone:this.materials.wood,[span,bridge.collision.deckThickness,width],[0,deck.startHeight-bridge.crossingCentre.y-bridge.collision.deckThickness/2,0]));
  const deckTop=deck.startHeight-bridge.crossingCentre.y,rampLength=bridge.collision.surfaces[1]!.length,rampMaterial=stone?this.materials.stone:this.materials.wood;
  for(const [side,bankHeight] of [[-1,bridge.bankElevations.left],[1,bridge.bankElevations.right]] as const){const outerTop=bankHeight-bridge.crossingCentre.y+.04,rise=Math.max(.04,deckTop-outerTop),angle=Math.atan2(rise,rampLength),length=Math.hypot(rampLength,rise),ramp=this.component(side<0?"left-entry-ramp":"right-entry-ramp",this.box,rampMaterial,[length,.16,width],[side*(span/2+rampLength/2),(deckTop+outerTop)/2-.08,0]);ramp.rotation.z=-side*angle;root.add(ramp);}
  if(stone){root.add(this.component("left-stone-parapet",this.box,this.materials.stoneDark,[span,.7,.28],[0,.5,-width/2+.14]),this.component("right-stone-parapet",this.box,this.materials.stoneDark,[span,.7,.28],[0,.5,width/2-.14]));for(const x of[-span/2+.35,span/2-.35])root.add(this.component("stone-abutment",this.box,this.materials.stoneDark,[.7,1.1,width+.6],[x,-.35,0]));if(bridge.variant==="single-arch")root.add(this.component("simplified-arch-pier",this.box,this.materials.stoneDark,[.65,.75,width-.5],[0,-.5,0]));}
  else {const beamCount=heavy?3:2;for(let i=0;i<beamCount;i++){const z=(i/(beamCount-1)-.5)*(width-.35);root.add(this.component("longitudinal-beam",this.box,this.materials.darkWood,[span,.28,.22],[0,-.18,z]));}const rail=heavy||bridge.variant!=="bare-plank";if(rail)for(const z of[-width/2+.1,width/2-.1]){root.add(this.component("bridge-railing",this.box,bridge.variant==="rope-railed"?this.materials.rope:this.materials.darkWood,[span,.14,.13],[0,.75,z]));for(let x=-span/2+.25;x<span/2;x+=heavy?1.8:2.5)root.add(this.component("railing-post",this.cylinder,this.materials.darkWood,[.16,1.35,.16],[x,.42,z]));}if(heavy&&bridge.variant==="trestle")for(const x of[-span*.25,span*.25])root.add(this.component("trestle",this.box,this.materials.darkWood,[.35,1.3,width-.3],[x,-.7,0]));}
  root.traverse(o=>{o.updateMatrix();o.matrixAutoUpdate=false;});return root;}
 createDebug(candidates:readonly BridgeCrossingCandidate[]):THREE.Group{const root=new THREE.Group();root.name="debug:bridge-crossings";root.userData.candidates=candidates;const vertices:number[]=[];const line=(a:{x:number;z:number},b:{x:number;z:number},y=.25)=>vertices.push(a.x,y,a.z,b.x,y,b.z);for(const c of candidates){line({x:c.centre.x-c.riverTangent.x*3,z:c.centre.z-c.riverTangent.z*3},{x:c.centre.x+c.riverTangent.x*3,z:c.centre.z+c.riverTangent.z*3});line(c.leftBankAnchor,c.rightBankAnchor,.32);line(c.approachPoints.left,c.leftBankAnchor,.35);line(c.rightBankAnchor,c.approachPoints.right,.35);}if(vertices.length){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(vertices,3));root.add(new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({color:0x43e7ff,depthTest:false})));}return root;}
 dispose():void{this.box.dispose();this.cylinder.dispose();Object.values(this.materials).forEach(m=>m.dispose());}
}
