import { sampleBiome, type BiomeId } from "./biomes";
import { CHUNK_SIZE, worldToChunk, type ChunkCoordinate } from "./chunkCoordinates";
import { footprintsOverlap, type GeneratedPoi, type PoiFootprint, type PoiZone } from "./poi";
import { hashFloat, normalizeSeed } from "./random";
import { RIVER_BANK_WIDTH, RIVER_TRANSITION_WIDTH, sampleNaturalTerrainHeight, sampleRiverCrossSection } from "./terrainSampling";

export type BridgeArchetype = "pedestrian-footbridge" | "heavy-timber-bridge" | "stone-bridge";
export type BridgeVariant = "bare-plank" | "rope-railed" | "low-timber-railed" | "simple-beam" | "trestle" | "reinforced-timber" | "shallow-stone-span" | "single-arch" | "hump-backed-stone";
export interface SpanRules { readonly minimumSpan?:number; readonly maximumSpan?:number; readonly preferredSpan?:number }
export interface BridgeArchetypeDefinition { readonly id:BridgeArchetype;readonly deckWidth:readonly[number,number];readonly spanRules:SpanRules;readonly rarity:number;readonly approachLength:number;readonly variants:readonly BridgeVariant[] }

/** Span limits are suitability hints, not river-width classes; every range includes today's channel. */
export const BRIDGE_ARCHETYPES:Readonly<Record<BridgeArchetype,BridgeArchetypeDefinition>>={
  "pedestrian-footbridge":{id:"pedestrian-footbridge",deckWidth:[1.2,1.8],spanRules:{minimumSpan:3,maximumSpan:18,preferredSpan:7},rarity:1,approachLength:3,variants:["bare-plank","rope-railed","low-timber-railed"]},
  "heavy-timber-bridge":{id:"heavy-timber-bridge",deckWidth:[2.8,3.8],spanRules:{minimumSpan:3,maximumSpan:24,preferredSpan:9},rarity:.62,approachLength:5,variants:["simple-beam","trestle","reinforced-timber"]},
  "stone-bridge":{id:"stone-bridge",deckWidth:[3.5,5],spanRules:{minimumSpan:3,maximumSpan:30,preferredSpan:10},rarity:.28,approachLength:6.5,variants:["shallow-stone-span","single-arch","hump-backed-stone"]},
};
export interface BridgePoint {readonly x:number;readonly y:number;readonly z:number}
export interface GeneratedBridge {
 readonly id:string;readonly ownerChunk:ChunkCoordinate;readonly crossingCentre:BridgePoint;readonly riverTangent:Readonly<{x:number;z:number}>;readonly crossingDirection:Readonly<{x:number;z:number}>;
 readonly leftBankAnchor:BridgePoint;readonly rightBankAnchor:BridgePoint;readonly spanLength:number;readonly bankElevations:Readonly<{left:number;right:number}>;readonly deckWidth:number;
 readonly archetype:BridgeArchetype;readonly variant:BridgeVariant;readonly approachPoints:Readonly<{left:BridgePoint;right:BridgePoint}>;readonly zones:readonly PoiZone[];
 readonly shadowCaster?:Readonly<{x:number;z:number;width:number;depth:number;rotation:number;height:number}>;readonly connections:Readonly<{left?:string;right?:string}>;
 readonly scale:Readonly<{span:number;width:number;profileHeight:number}>;
}
export type BridgeRejectionReason="rarity"|"river too curved"|"approach slope too high"|"unstable banks"|"building conflict"|"bridge spacing";
export interface BridgeCrossingCandidate {readonly id:string;readonly ownerChunk:ChunkCoordinate;readonly centre:Readonly<{x:number;z:number}>;readonly riverTangent:Readonly<{x:number;z:number}>;readonly crossingDirection:Readonly<{x:number;z:number}>;readonly leftBankAnchor:BridgePoint;readonly rightBankAnchor:BridgePoint;readonly approachPoints:Readonly<{left:BridgePoint;right:BridgePoint}>;readonly spanLength:number;readonly approachSlope:number;readonly bankStability:number;readonly biome:BiomeId;readonly accepted:boolean;readonly reason?:BridgeRejectionReason;readonly archetype?:BridgeArchetype}

const BIOME_SCORE:Record<BiomeId,Record<BridgeArchetype,number>>={
 forest:{"pedestrian-footbridge":1,"heavy-timber-bridge":.82,"stone-bridge":.16},wetland:{"pedestrian-footbridge":1,"heavy-timber-bridge":.68,"stone-bridge":-.8},plains:{"pedestrian-footbridge":.52,"heavy-timber-bridge":1,"stone-bridge":.7},highlands:{"pedestrian-footbridge":.18,"heavy-timber-bridge":.58,"stone-bridge":1},mountain:{"pedestrian-footbridge":.12,"heavy-timber-bridge":.5,"stone-bridge":.95},lake:{"pedestrian-footbridge":.35,"heavy-timber-bridge":.35,"stone-bridge":-.8},
};
export function spanSuitability(archetype:BridgeArchetype,span:number):number{const r=BRIDGE_ARCHETYPES[archetype].spanRules;if((r.minimumSpan!==undefined&&span<r.minimumSpan)||(r.maximumSpan!==undefined&&span>r.maximumSpan))return .15;return r.preferredSpan===undefined?1:Math.max(.55,1-Math.abs(span-r.preferredSpan)/Math.max(span,r.preferredSpan));}
export function scoreBridgeArchetypes(seed:number,candidate:Pick<BridgeCrossingCandidate,"id"|"biome"|"spanLength"|"approachSlope"|"bankStability"|"leftBankAnchor"|"rightBankAnchor">):Readonly<Record<BridgeArchetype,number>>{const difference=Math.abs(candidate.leftBankAnchor.y-candidate.rightBankAnchor.y);return Object.fromEntries((Object.keys(BRIDGE_ARCHETYPES) as BridgeArchetype[]).map((id,index)=>{const d=BRIDGE_ARCHETYPES[id];let score=BIOME_SCORE[candidate.biome][id]+spanSuitability(id,candidate.spanLength)*.15+d.rarity*.08+hashFloat(seed,Math.floor(candidate.leftBankAnchor.z),index,1601)*.24-candidate.approachSlope*(id==="pedestrian-footbridge"?1.3:2.2)-difference*(id==="stone-bridge"?.07:.14);if(id==="stone-bridge")score+=(candidate.bankStability-.55)*.7;return[id,score];})) as Record<BridgeArchetype,number>}

function rawCandidate(seed:number,row:number):BridgeCrossingCandidate|undefined{const z=(row+.5)*CHUNK_SIZE,section=sampleRiverCrossSection(seed,CHUNK_SIZE/2,z);if(!section)return;const before=sampleRiverCrossSection(seed,CHUNK_SIZE/2,z-2),after=sampleRiverCrossSection(seed,CHUNK_SIZE/2,z+2);if(!before||!after)return;const tx=after.centerX-before.centerX,tz=4,length=Math.hypot(tx,tz),tangent={x:tx/length,z:tz/length},direction={x:tangent.z,z:-tangent.x};const shoulder=section.waterWidth/2+RIVER_BANK_WIDTH+RIVER_TRANSITION_WIDTH+.35;const point=(side:number,distance:number)=>{const x=section.centerX+direction.x*distance*side,pz=z+direction.z*distance*side;return{x,y:sampleNaturalTerrainHeight(seed,x,pz),z:pz}};const left=point(-1,shoulder),right=point(1,shoulder),approachDistance=shoulder+6,leftApproach=point(-1,approachDistance),rightApproach=point(1,approachDistance);const slope=Math.max(Math.abs(leftApproach.y-left.y),Math.abs(rightApproach.y-right.y))/6,stability=Math.max(0,1-slope*3-hashFloat(seed,row,1701)*.18),owner=worldToChunk(section.centerX,z),id=`bridge:${seed.toString(16)}:${row}`;return{id,ownerChunk:owner,centre:{x:section.centerX,z},riverTangent:tangent,crossingDirection:direction,leftBankAnchor:left,rightBankAnchor:right,approachPoints:{left:leftApproach,right:rightApproach},spanLength:shoulder*2,approachSlope:slope,bankStability:stability,biome:sampleBiome(seed,section.centerX,z).dominant,accepted:false};}
function candidatePriority(seed:number,row:number):number{return hashFloat(seed,row,1801)}
export function generateBridges(seedInput:number|string,coordinate:ChunkCoordinate,obstacles:readonly GeneratedPoi[]=[]):Readonly<{bridges:readonly GeneratedBridge[];candidates:readonly BridgeCrossingCandidate[]}>{const seed=normalizeSeed(seedInput);if(coordinate.x!==0)return{bridges:[],candidates:[]};const row=coordinate.z,c=rawCandidate(seed,row);if(!c)return{bridges:[],candidates:[]};let reason:BridgeRejectionReason|undefined;if(candidatePriority(seed,row)>.58)reason="rarity";else {for(let offset=-3;offset<=3;offset++)if(offset&&candidatePriority(seed,row+offset)<candidatePriority(seed,row)){reason="bridge spacing";break;}}if(!reason&&c.approachSlope>.22)reason="approach slope too high";else if(!reason&&c.bankStability<.3)reason="unstable banks";const scores=scoreBridgeArchetypes(seed,c);const archetype=(Object.keys(scores) as BridgeArchetype[]).sort((a,b)=>scores[b]-scores[a]||a.localeCompare(b))[0]!;const definition=BRIDGE_ARCHETYPES[archetype],rotation=Math.atan2(c.crossingDirection.z,c.crossingDirection.x),deck:PoiFootprint={kind:"rectangle",x:c.centre.x,z:c.centre.z,halfWidth:c.spanLength/2,halfDepth:(definition.deckWidth[1]+.8)/2,rotation};if(!reason&&obstacles.some(p=>p.zones.some(z=>z.purpose==="solid"&&footprintsOverlap(deck,z.footprint))))reason="building conflict";const debug={...c,accepted:!reason,reason,archetype:reason?undefined:archetype};if(reason)return{bridges:[],candidates:[debug]};const width=definition.deckWidth[0]+hashFloat(seed,row,1901)*(definition.deckWidth[1]-definition.deckWidth[0]),variant=definition.variants[Math.floor(hashFloat(seed,row,1911)*definition.variants.length)]!,centreY=Math.max(c.leftBankAnchor.y,c.rightBankAnchor.y)+.18,approachHalf=definition.approachLength/2;const approachZone=(p:BridgePoint,side:number):PoiZone=>({name:"bridge-approach",purpose:"vegetation-exclusion",footprint:{kind:"rectangle",x:(p.x+(side<0?c.leftBankAnchor.x:c.rightBankAnchor.x))/2,z:(p.z+(side<0?c.leftBankAnchor.z:c.rightBankAnchor.z))/2,halfWidth:approachHalf,halfDepth:width*.72,rotation}});const zones:PoiZone[]=[{name:"bridge-deck",purpose:"solid",footprint:deck},{name:"bridge-clearance",purpose:"vegetation-exclusion",footprint:{...deck,halfDepth:width*.8}},approachZone(c.approachPoints.left,-1),approachZone(c.approachPoints.right,1)];const bridge:GeneratedBridge={id:c.id,ownerChunk:{...c.ownerChunk},crossingCentre:{x:c.centre.x,y:centreY,z:c.centre.z},riverTangent:c.riverTangent,crossingDirection:c.crossingDirection,leftBankAnchor:c.leftBankAnchor,rightBankAnchor:c.rightBankAnchor,spanLength:c.spanLength,bankElevations:{left:c.leftBankAnchor.y,right:c.rightBankAnchor.y},deckWidth:width,archetype,variant,approachPoints:c.approachPoints,zones,connections:{},scale:{span:c.spanLength,width,profileHeight:archetype==="stone-bridge"?.65:archetype==="heavy-timber-bridge"?.22:.3},shadowCaster:{x:c.centre.x,z:c.centre.z,width:c.spanLength,depth:width,rotation,height:centreY}};return{bridges:[bridge],candidates:[debug]};}
