import * as THREE from "three";
import type { GeneratedPoi, PoiDebugCandidate, PoiFootprint } from "./poi";

export interface PoiDebugOptions { readonly level:"off"|"accepted"|"candidates" }

/** Presentation-only registry of low-poly POI renderers and shared components. */
export class PoiMeshFactory {
  private readonly renderers=new Map<string,(poi:GeneratedPoi)=>THREE.Object3D>();
  private readonly box=this.shared(new THREE.BoxGeometry(1,1,1));
  private readonly roof=this.shared(createRoofGeometry());
  private readonly cylinder=this.shared(new THREE.CylinderGeometry(.5,.5,1,6));
  private readonly materials={wall:new THREE.MeshStandardMaterial({color:0xd8c49f,roughness:1}),lakeWall:new THREE.MeshStandardMaterial({color:0xa8b6a4,roughness:1}),roof:new THREE.MeshStandardMaterial({color:0x8d5f51,roughness:1,flatShading:true}),wood:new THREE.MeshStandardMaterial({color:0x80674d,roughness:1}),darkWood:new THREE.MeshStandardMaterial({color:0x57483d,roughness:1}),door:new THREE.MeshStandardMaterial({color:0x6e4b3d,roughness:1}),window:new THREE.MeshStandardMaterial({color:0x9fc7cf,roughness:.65}),chimney:new THREE.MeshStandardMaterial({color:0x786b62,roughness:1}),foliage:new THREE.MeshStandardMaterial({color:0x779465,roughness:1,flatShading:true})};
  private readonly debugMaterial=new THREE.LineBasicMaterial({color:0xffcc44,depthTest:false});
  private readonly acceptedDebugMaterial=new THREE.MeshBasicMaterial({color:0x32ff72,transparent:true,opacity:.78,depthTest:false,depthWrite:false});
  private readonly rejectedDebugMaterial=new THREE.MeshBasicMaterial({color:0xff285f,transparent:true,opacity:.68,depthTest:false,depthWrite:false});
  constructor(){this.register("plains-farmhouse",poi=>this.buildHouse(poi,false));this.register("lake-house",poi=>this.buildHouse(poi,true));}
  register(typeId:string,renderer:(poi:GeneratedPoi)=>THREE.Object3D):void{this.renderers.set(typeId,renderer);}
  create(poi:GeneratedPoi):THREE.Group{const root=new THREE.Group();root.name=`poi:${poi.typeId}:${poi.id}`;root.userData={poiId:poi.id,poiType:poi.typeId};root.position.set(poi.position.x,poi.position.y,poi.position.z);root.rotation.y=poi.rotation;const renderer=this.renderers.get(poi.typeId);if(renderer)root.add(renderer(poi));freezeStaticTree(root);return root;}
  private component(name:string,material:THREE.Material,scale:[number,number,number],position:[number,number,number],geometry:THREE.BufferGeometry=this.box):THREE.Mesh{const mesh=new THREE.Mesh(geometry,material);mesh.name=name;mesh.scale.set(...scale);mesh.position.set(...position);return mesh;}
  private buildHouse(poi:GeneratedPoi,lakeside:boolean):THREE.Group{const group=new THREE.Group();group.name=lakeside?"lake-house-components":"farmhouse-components";const wall=lakeside?this.materials.lakeWall:this.materials.wall;group.add(this.component("foundation",this.materials.darkWood,[6.2,.45,5.2],[0,.15,0]),this.component("walls",wall,[5.7,2.8,4.7],[0,1.72,0]),this.component("pitched-roof",this.materials.roof,[6.5,1.65,5.35],[0,3.1,0],this.roof),this.component("front-door",this.materials.door,[1.05,2,.12],[0,1.3,2.42]),this.component("front-window-left",this.materials.window,[1.05,.85,.1],[-1.75,1.95,2.44]),this.component("front-window-right",this.materials.window,[1.05,.85,.1],[1.75,1.95,2.44]),this.component("side-window",this.materials.window,[.1,.9,1.2],[2.88,1.95,0]),this.component("chimney",this.materials.chimney,[.62,2,.62],[-1.65,4.05,-.5]));
    if(lakeside){group.add(this.component("porch",this.materials.wood,[4,.22,1.25],[0,.55,2.85]));this.addDock(group,poi);this.addBench(group);}
    else{this.addFence(group);for(const tree of poi.decorativeTrees??[]){const local=worldToLocal(poi,tree.x,tree.z),treeGroup=new THREE.Group();treeGroup.name="poi-owned-tree";treeGroup.position.set(local.x,0,local.z);treeGroup.scale.setScalar(tree.scale);treeGroup.add(this.component("trunk",this.materials.wood,[.42,2.3,.42],[0,1.15,0],this.cylinder),this.component("crown",this.materials.foliage,[2.2,3,2.2],[0,3,0],this.cylinder));group.add(treeGroup);}}
    return group;}
  private addFence(group:THREE.Group):void{const add=(x:number,z:number,sx:number,sz:number)=>{group.add(this.component("fence-rail",this.materials.wood,[sx,.18,sz],[x,.72,z]));const span=sx>sz?sx:sz;for(const side of[-1,1])group.add(this.component("fence-post",this.materials.darkWood,[.2,1.2,.2],[x+(sx>sz?side*span/2:0),.6,z+(sz>sx?side*span/2:0)]));};add(-4.7,-3.8,5.5,.16);add(4.7,-3.8,5.5,.16);add(-6.9,0,.16,7.7);add(6.9,0,.16,7.7);add(-4.7,3.8,4.1,.16);add(4.7,3.8,4.1,.16);}
  private addDock(group:THREE.Group,poi:GeneratedPoi):void{if(!poi.dock)return;const center=poi.dock.footprint.kind==="rectangle"?worldToLocal(poi,poi.dock.footprint.x,poi.dock.footprint.z):{x:0,z:5};const length=poi.dock.footprint.kind==="rectangle"?poi.dock.footprint.halfDepth*2:5;const localY=poi.dock.surfaceElevation+.12-poi.position.y;for(let z=-length/2+.35;z<length/2;z+=.7)group.add(this.component("dock-plank",this.materials.wood,[2.1,.16,.62],[center.x,localY,center.z+z]));for(const x of[-1,1])for(const z of[-length/2+.3,length/2-.3])group.add(this.component("dock-post",this.materials.darkWood,[.18,1.25,.18],[center.x+x,localY-.42,center.z+z],this.cylinder));}
  private addBench(group:THREE.Group):void{group.add(this.component("bench-seat",this.materials.wood,[2,.18,.55],[-3.9,.8,1.2]),this.component("bench-back",this.materials.wood,[2,.75,.15],[-3.9,1.2,.95]));}
  createDebug(pois:readonly GeneratedPoi[],candidates:readonly PoiDebugCandidate[],level:Exclude<PoiDebugOptions["level"],"off">):THREE.Group{const root=new THREE.Group();root.name="debug:pois";root.userData.level=level;const positions:number[]=[];const segment=(a:THREE.Vector3,b:THREE.Vector3)=>positions.push(a.x,a.y,a.z,b.x,b.y,b.z);for(const poi of pois){for(const zone of poi.zones){const points=outlinePoints(zone.footprint,poi.position.y+.08);for(let i=0;i<points.length;i++)segment(points[i]!,points[(i+1)%points.length]!);}segment(new THREE.Vector3(poi.position.x,poi.position.y+.12,poi.position.z),new THREE.Vector3(poi.entrance.position.x,poi.position.y+.12,poi.entrance.position.z));if(poi.dock)segment(new THREE.Vector3(poi.dock.shore.x,poi.dock.surfaceElevation+.2,poi.dock.shore.z),new THREE.Vector3(poi.dock.end.x,poi.dock.surfaceElevation+.2,poi.dock.end.z));}if(positions.length){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));const lines=new THREE.LineSegments(geometry,this.debugMaterial);lines.name="debug:poi-lines";root.add(lines);}const visibleCandidates=level==="candidates"?candidates:candidates.filter(candidate=>candidate.accepted);this.addCandidateBatch(root,visibleCandidates.filter(candidate=>candidate.accepted),true);this.addCandidateBatch(root,visibleCandidates.filter(candidate=>!candidate.accepted),false);freezeStaticTree(root);return root;}
  private addCandidateBatch(root:THREE.Group,candidates:readonly PoiDebugCandidate[],accepted:boolean):void{if(!candidates.length)return;const batch=new THREE.InstancedMesh(this.cylinder,accepted?this.acceptedDebugMaterial:this.rejectedDebugMaterial,candidates.length);batch.name=accepted?"debug:poi-candidates:accepted":"debug:poi-candidates:rejected";batch.userData.candidates=candidates;batch.renderOrder=100;const transform=new THREE.Object3D();candidates.forEach((candidate,index)=>{transform.position.set(candidate.x,.16,candidate.z);transform.scale.set(2.8,.22,2.8);transform.updateMatrix();batch.setMatrixAt(index,transform.matrix);});batch.instanceMatrix.needsUpdate=true;root.add(batch);}
  private shared<T extends THREE.BufferGeometry>(geometry:T):T{geometry.userData.poiShared=true;return geometry;}
  dispose():void{this.box.dispose();this.roof.dispose();this.cylinder.dispose();for(const material of Object.values(this.materials))material.dispose();this.debugMaterial.dispose();this.acceptedDebugMaterial.dispose();this.rejectedDebugMaterial.dispose();}
}
function outlinePoints(shape:PoiFootprint,y:number):THREE.Vector3[]{return shape.kind==="circle"?Array.from({length:24},(_,i)=>new THREE.Vector3(shape.x+Math.cos(i*Math.PI/12)*shape.radius,y,shape.z+Math.sin(i*Math.PI/12)*shape.radius)):Array.from({length:4},(_,i)=>{const u=i===0||i===3?-1:1,v=i<2?-1:1,c=Math.cos(shape.rotation),s=Math.sin(shape.rotation);return new THREE.Vector3(shape.x+c*shape.halfWidth*u-s*shape.halfDepth*v,y,shape.z+s*shape.halfWidth*u+c*shape.halfDepth*v);});}
function freezeStaticTree(root:THREE.Object3D):void{root.traverse(object=>{object.updateMatrix();object.matrixAutoUpdate=false;});}
function worldToLocal(poi:GeneratedPoi,x:number,z:number):{x:number;z:number}{const dx=x-poi.position.x,dz=z-poi.position.z,c=Math.cos(poi.rotation),s=Math.sin(poi.rotation);return{x:dx*c-dz*s,z:dx*s+dz*c};}
export function createRoofGeometry():THREE.BufferGeometry{const vertices=[-0.5,-0.5,-0.5,.5,-.5,-.5,0,.5,-.5,-.5,-.5,.5,.5,-.5,.5,0,.5,.5],indices=[0,2,1,3,4,5,0,3,4,0,4,1,1,4,5,1,5,2,2,5,3,2,3,0];const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}
